### ISSUE TITLE
Chapter 18 (trend analysis), how to retrieve year?

### ISSUE THREAD

**Issue by jinjinzhou** [MIT-LCP/critical-data-book#14]
In the chartevents.csv table we downloaded, 

one CHARTTIME, is  5/12/34 12:00

Can someone help with what does 34 mean? How to translate to 34 to a correct calendar year. 

Thanks

Jin

**Comment by jraffa** [comment]
If you're extracting this from MIMIC II or III, the dates have been shifted, and the years should be nonsensical as the shifting is necessary to protect PHI.  It is possible to apply for access to get the actual years, and I would e-mail mimic-support@physionet.org to ask how. 

I am not certain, but the authors likely applied for this additional access themselves, and this was how they were able to write their chapter. 

Since this isn't a question related to the code, I will close the issue, but if I have misunderstood, feel free to let me know.

**Comment by tompollard** [comment]
@jinjinzhou as Jesse mentions, the dates are shifted by several hundred years for de-identification purposes. Are you looking at the raw text or using an application like Excel? Excel mashes up the shifted dates, which might explain why you are seeing a nonsensical value.

**Comment by jinjinzhou** [comment]
Thanks, Jesse and Tom. We are using MIMIC-III. I am ccing <email address removed> to see if any algorithm we may have to translate year.

Thanks,

Jin

**Comment by tompollard** [comment]
@jinjinzhou There is no need to email us. We prefer to discuss these issues on the public repository (as noted at: https://mimic.physionet.org/help/). 

You can typically treat the dates in MIMIC as standard dates. It should not be necessary to translate them. What software are you using the view the data?

**Comment by jinjinzhou** [comment]
Thanks, Tom. I followed instruction as noted in MIMIC-III to a postgres SQL database and vied them by R.

Jin

**Comment by tompollard** [comment]
The date that you've listed above (CHARTTIME, is 5/12/34 12:00) does not occur in MIMIC-III as far as I am aware. If this date appears in your database, please provide us with a query to find this value (e.g. `select charttime from chartevents where row_id = X`). Please also read https://www.nature.com/articles/sdata201635 and https://mimic.physionet.org/mimicdata/time/ if you have not already done so.

**Comment by jraffa** [comment]
How are you viewing it in R?  Are you using `RPostgreSQL`?

**Comment by jinjinzhou** [comment]
Yes

**Comment by jraffa** [comment]
It is difficult to diagnosis this if we can't replicate it on our end.  Are you are able to find what @tompollard has asked for?  (`row_id`)

**Comment by jinjinzhou** [comment]
Here it looks like.

Jin

[cid:image001.png@01D488AD.8181E380]

**Comment by jraffa** [comment]
Jin, can you post the image on github.com, it's not showing up here.
https://github.com/MIT-LCP/critical-data-book/issues/14

**Comment by jinjinzhou** [comment]
<img width="621" alt="screen shot 2018-11-30 at 12 58 02 pm" src="https://user-images.githubusercontent.com/13785167/49316512-63c2d580-f4ae-11e8-91bc-e7ca8888063a.png">

**Comment by tompollard** [comment]
@jinjinzhou this is an Excel screenshot. As mentioned, Excel messes with the values. Try looking at the raw data (e.g. in a plain text editor).

**Comment by jinjinzhou** [comment]
<img width="443" alt="screen shot 2018-11-30 at 2 55 44 pm" src="https://user-images.githubusercontent.com/13785167/49317034-30814600-f4b0-11e8-8984-e2a726800e06.png">

**Comment by MizzleChen** [comment]
> Jin, can you post the image on github.com, it's not showing up here.
> #14

The data set description about chartevents.csv is available from the website https://mimic.physionet.org/mimictables/chartevents/
The dates are all shifted based on the website https://mimic.physionet.org/mimicdata/time/
It seems that only year had been shifted. Month and day are from original record. 
I am just wondering is there anyway to find original year for each observation.

**Comment by jinjinzhou** [comment]
To echo above comment, we don't need to have exact year - just a number in the same order as the calendar year order. Thanks,

**Comment by tompollard** [comment]
The year (or sequence by year) is not available in MIMIC-III unfortunately. We understand that this is a limitation and are considering alternative options for handling de-identification for the next release of MIMIC.
