### ISSUE TITLE
section 3: chapter04_code.R mangled

### ISSUE THREAD

**Issue by jraffa** [MIT-LCP/critical-data-book#4]
Looks like some encoding issues with the `chapter04_code.R`file.  I noticed it only because github is detecting it as rebol.

**Comment by tompollard** [comment]
Thanks Jesse. Can you explain a little bit more for @peterhcharlton, so he can look into this?

**Comment by jraffa** [comment]
It looks like it was pasted from a source which was HTML, and didn't paste well.  It has HTML style special characters.  `e.g., &quot; instead of "`

**Comment by peterhcharlton** [comment]
Many thanks @jraffa , I've amended the `chapter04_code.R` file and I think it's now fixed.

**Comment by jraffa** [comment]
Looks good.  Thanks!
