### ISSUE TITLE
Code in Section 2, Chapter 3c contains several files with a .m~ extension

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/critical-data-book#5]
The code for Section 2, Chapter 3c needs a fair amount of work to make it easy to follow and reuse:
https://github.com/MIT-LCP/critical-data-book/tree/master/section2/chapter3c/code

One issue is that the code includes several files with the .m~ extension, which I assume are temporary files. In some cases these were duplicates of other files, so I removed them, but there are still some remaining. 

Should the .m~ files be renamed with a .m extension or can they be removed?

**Comment by alistairewj** [comment]
.m~ files are automatically generated backup files (same as .asv). Since
we're using github they're redundant and can be removed.

**Comment by tompollard** [comment]
> .m~ files are automatically generated backup files (same as .asv). Since we're using github they're redundant and can be removed.

These are new files that I copied from Dropbox and committed to Github. I deleted most of the temporary files before the first commit, but kept the ones that weren't obviously a duplicate of another file. Just want to check that they are duplicates before deleting them.

**Comment by tompollard** [comment]
yep, so they are all archived versions of files in the parent folder, which is why I missed them:
- [chapter3c/code/main_missing_data_comparison.m~](https://github.com/MIT-LCP/critical-data-book/blob/master/section2/chapter3c/code/main_missing_data_comparison.m~) => [chapter3c/make_histograms.m](https://github.com/MIT-LCP/critical-data-book/blob/master/section2/chapter3c/make_histograms.m).
- [chapter3c/code/main_data_histograms.m~](https://github.com/MIT-LCP/critical-data-book/blob/master/section2/chapter3c/code/main_data_histograms.m~) => [chapter3c/main_data_histograms.m](https://github.com/MIT-LCP/critical-data-book/blob/master/section2/chapter3c/main_data_histograms.m)
- [chapter3c/code/make_histograms.m~](https://github.com/MIT-LCP/critical-data-book/blob/master/section2/chapter3c/code/make_histograms.m~) => [chapter3c/make_histograms.m](https://github.com/MIT-LCP/critical-data-book/blob/master/section2/chapter3c/make_histograms.m).
