### ISSUE TITLE
Chapter #s

### ISSUE THREAD

**Issue by jraffa** [MIT-LCP/critical-data-book#9]
The proofs seem to have different chapter numbers than what is listed here.  

They should obviously match.

**Comment by jraffa** [comment]
Had an e-mail from a colleague looking for the noise vs outlier chapter code.  It's incredibly hard to navigate due to this issue.

**Comment by tompollard** [comment]
It will be difficult to get the code into a clean state because of the way that it was provided. As a start I'll take a look at cleaning up the chapter numbers.

**Comment by peterhcharlton** [comment]
Thanks it's a good point Jesse. I'll be able to have a look at Section 3 and modify the chapter numbers appropriately next week.

**Comment by tompollard** [comment]
The code still needs a big clean up, but the chapter labels have been updated so I am closing this issue.
